name: pgp
description: OpenPGP and Sequoia bindings for Dart.
version: 0.0.1-dev.2
repository: https://github.com/ManyMath/pgp-dart

environment:
  sdk: ^3.6.0-0

dependencies:
  native_toolchain_rust_mirror: ^0.1.0-dev.8
  native_assets_cli: ^0.7.2
  ffi: ^2.1.3
  ffigen: ^14.0.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
