// ignore_for_file: always_specify_types
// ignore_for_file: camel_case_types
// ignore_for_file: non_constant_identifier_names

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint
import 'dart:ffi' as ffi;

/// Bindings for `pgp-ffi`.  See the README for how to use this file.
///
class PgpFfiBindings {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  PgpFfiBindings(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  PgpFfiBindings.fromLookup(
      ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
          lookup)
      : _lookup = lookup;

  /// # Safety
  /// `cert` must be non-null and from a `pgp_certificate_*` constructor.
  void pgp_certificate_free(
    ffi.Pointer<Certificate> cert,
  ) {
    return _pgp_certificate_free(
      cert,
    );
  }

  late final _pgp_certificate_freePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<Certificate>)>>(
          'pgp_certificate_free');
  late final _pgp_certificate_free = _pgp_certificate_freePtr
      .asFunction<void Function(ffi.Pointer<Certificate>)>();

  /// # Safety
  /// `key` must be non-null and from a `pgp_key_*` constructor.
  void pgp_key_free(
    ffi.Pointer<Key> key,
  ) {
    return _pgp_key_free(
      key,
    );
  }

  late final _pgp_key_freePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<Key>)>>(
          'pgp_key_free');
  late final _pgp_key_free =
      _pgp_key_freePtr.asFunction<void Function(ffi.Pointer<Key>)>();

  /// # Safety
  /// `user_id` must be non-null and from a `pgp_user_id_*` constructor.
  void pgp_user_id_free(
    ffi.Pointer<UserID> user_id,
  ) {
    return _pgp_user_id_free(
      user_id,
    );
  }

  late final _pgp_user_id_freePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<UserID>)>>(
          'pgp_user_id_free');
  late final _pgp_user_id_free =
      _pgp_user_id_freePtr.asFunction<void Function(ffi.Pointer<UserID>)>();

  /// Parse an ASCII-armored PGP cert into `*cert`.
  ///
  /// # Safety
  /// `armored` and `cert` must be non-null.
  int pgp_certificate_from_armored(
    ffi.Pointer<ffi.Char> armored,
    ffi.Pointer<ffi.Pointer<Certificate>> cert,
  ) {
    return _pgp_certificate_from_armored(
      armored,
      cert,
    );
  }

  late final _pgp_certificate_from_armoredPtr = _lookup<
          ffi.NativeFunction<
              ffi.Int32 Function(ffi.Pointer<ffi.Char>,
                  ffi.Pointer<ffi.Pointer<Certificate>>)>>(
      'pgp_certificate_from_armored');
  late final _pgp_certificate_from_armored =
      _pgp_certificate_from_armoredPtr.asFunction<
          int Function(
              ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Pointer<Certificate>>)>();

  /// Generate a new certificate with the given user ID.
  ///
  /// # Safety
  /// `user_id` and `new_cert` must be non-null.
  int pgp_key_generate(
    ffi.Pointer<ffi.Char> user_id,
    ffi.Pointer<ffi.Pointer<Certificate>> new_cert,
  ) {
    return _pgp_key_generate(
      user_id,
      new_cert,
    );
  }

  late final _pgp_key_generatePtr = _lookup<
      ffi.NativeFunction<
          ffi.Int32 Function(ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Pointer<Certificate>>)>>('pgp_key_generate');
  late final _pgp_key_generate = _pgp_key_generatePtr.asFunction<
      int Function(
          ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Pointer<Certificate>>)>();
}

final class Certificate extends ffi.Opaque {}

final class Key extends ffi.Opaque {}

final class UserID extends ffi.Opaque {}
